### ISSUE TITLE
Overrides at start

### ISSUE THREAD

**Issue by Swepool** [ivanhofer/typesafe-i18n-demo-sveltekit-jsdoc#1]
If I run npm i then npm run dev it adds all .ts files, don't know if there's a setting for this?

**Comment by ivanhofer** [comment]
Please take a look at the [`JSDoc` section](https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/generator#jsdoc) of the readme. If you set the `outputFormat` to `JavaScript`, you should not see any `.ts` files appear
