### ISSUE TITLE
navigation/popStateEvent error

### ISSUE THREAD

**Issue by b-lov** [ivanhofer/typesafe-i18n-demo-sveltekit-jsdoc#2]
hi, i get a state inconsistency when navigating to the page for the first time, switching locale and then immediately navigating backwards, see video:

https://user-images.githubusercontent.com/8249085/182708094-a69842b9-37e9-4213-a4b6-3b05f3eb3e77.mov

**Comment by ivanhofer** [comment]
Thanks for opening the issue. I have updated the `src/lib/LocaleSwitcher.svelte` file

**Comment by b-lov** [comment]
damn you're fast 😅
thanks for the awesome library!

Edit: the issue is solved for the initial load, however its still there when navigating to a route via anchor tag.

https://user-images.githubusercontent.com/8249085/182817739-4238a837-a4ba-4371-bfb9-4fe6166cbec3.mov

**Comment by ivanhofer** [comment]
oops ^^
can you please share your repo?

**Comment by b-lov** [comment]
you can also observe it in this repo. basically it always happens after an anchor tag is clicked. in this case after clicking the `<a href="/{$locale}">` tag from Header.svelte

https://user-images.githubusercontent.com/8249085/182939741-df9d0b65-0302-43bd-98d6-36457601cdab.mov

**Comment by ivanhofer** [comment]
Thanks. I found the issue and fixed the example: https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit-jsdoc/commit/0951bb995d4aa0dbf05d74ca293ac43628cca202

**Comment by b-lov** [comment]
thanks man, you're awesome.
changing languages and navigating backwards/forwards works fine now when staying on the same route. however when i navigate between different routes, the page content becomes stuck (see video). it used to work before the commit. it seems like it happens as soon as you put the `lang` variable inside the reactive block:
```javascript
$: if ( browser) {
	  const lang = /** @type { import('$i18n/i18n-types').Locales } page.params.lang */ ($page.params.lang)
	  switchLocale(lang, false)
	  history.replaceState({ locale: lang }, '', replaceLocaleInUrl(location.pathname, lang))
}
```
as soon as you take `lang` back to the outer scope, the problem diappears (but the old problem mentioned in my previous comment reappears). I wonder if there is a way of switching languages without messing with the history state.

my repo is at https://github.com/b-lov/nekomusicmedia.de_v2/tree/develop
it's basically the same as your example here without styling and one added route.

https://user-images.githubusercontent.com/8249085/183074026-6db1f8e4-b08f-46d8-82c5-f52ba69ea47f.mov

**Comment by ivanhofer** [comment]
@b-lov thanks for providing all the useful error-reproductions :)
It seems that SvelteKit uses the history.state object to handle backwards-navigation. I wasn't aware of that until now.
The latest commit should fix the issue https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit-jsdoc/commit/1413236864b5460abeee6ac1d1921a4349c56c51

**Comment by b-lov** [comment]
it works perfectly now, thank you so much for your time and effort!

also congrats on the generally amazing documentation of typesafe-i18n in the main repo, i found lots of answers to very specific problems i had.

best regards!

**Comment by ivanhofer** [comment]
Thanks for your kind words!
