### ISSUE TITLE
update repo?

### ISSUE THREAD

**Issue by b-lov** [ivanhofer/typesafe-i18n-demo-sveltekit-jsdoc#3]
hey, do you have plans to update this jsdoc version of the example with the newest changes from the typescript one ?
best regards

**Comment by ivanhofer** [comment]
Hi @b-lov,
I will update it once I find some time..

Here are the things that did change recentyl in the main repo: https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/compare/ab7ad40f363cf0d0af036c55e0810450cc4bb97d..7a5ce78ebf16d2371f5c27bee3f360410c82cda1

Nothing really changed regarding `TypeScript` vs `JsDoc`. Mostly some function calls were modified.

It would be great if someone could update this example with the changes mentioned above.

**Comment by b-lov** [comment]
thanks so much for your reply. i will try to update if i find the time (it would be my first PR outside my own repos, lol). best regards!

**Comment by ivanhofer** [comment]
Here you go https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit-jsdoc/commit/a9c2ce7ce28bc257ab4d28cf84e6235db519ec99
